export type Category =
  | 'Food & Drink'
  | 'Transportation'
  | 'Subscriptions'
  | 'Housing'
  | 'Groceries'
  | 'Health'
  | 'Fitness'
  | 'Uncategorized';

export const CATEGORIES: Category[] = [
  'Food & Drink',
  'Transportation',
  'Subscriptions',
  'Housing',
  'Groceries',
  'Health',
  'Fitness',
  'Uncategorized',
];

export const KEYWORD_CATEGORY_MAP: Record<string, Category> = {
  // Food & Drink
  coffee: 'Food & Drink',
  latte: 'Food & Drink',
  'tim hortons': 'Food & Drink',
  starbucks: 'Food & Drink',
  'second cup': 'Food & Drink',
  'dutch bros': 'Food & Drink',
  cafe: 'Food & Drink',
  restaurant: 'Food & Drink',
  pizza: 'Food & Drink',
  sushi: 'Food & Drink',
  burger: 'Food & Drink',
  'boston pizza': 'Food & Drink',
  'white spot': 'Food & Drink',
  "mcdonald's": 'Food & Drink',
  mcdonalds: 'Food & Drink',
  "wendy's": 'Food & Drink',
  wendys: 'Food & Drink',
  kfc: 'Food & Drink',
  subway: 'Food & Drink',
  chipotle: 'Food & Drink',
  'a&w': 'Food & Drink',
  'dairy queen': 'Food & Drink',
  "denny's": 'Food & Drink',
  dennys: 'Food & Drink',
  'harveys': 'Food & Drink',
  "harvey's": 'Food & Drink',
  'skip the dishes': 'Food & Drink',
  skipthedishes: 'Food & Drink',
  doordash: 'Food & Drink',
  'uber eats': 'Food & Drink',
  ubereats: 'Food & Drink',
  'east side marios': 'Food & Drink',
  'earls': 'Food & Drink',
  'browns socialhouse': 'Food & Drink',
  ramen: 'Food & Drink',
  thai: 'Food & Drink',
  pho: 'Food & Drink',
  brunch: 'Food & Drink',
  diner: 'Food & Drink',
  bakery: 'Food & Drink',
  // Transportation
  uber: 'Transportation',
  lyft: 'Transportation',
  gas: 'Transportation',
  transit: 'Transportation',
  parking: 'Transportation',
  skytrain: 'Transportation',
  bus: 'Transportation',
  taxi: 'Transportation',
  esso: 'Transportation',
  shell: 'Transportation',
  'petro-canada': 'Transportation',
  petrocanada: 'Transportation',
  'canadian tire': 'Transportation',
  enterprise: 'Transportation',
  hertz: 'Transportation',
  avis: 'Transportation',
  'bc ferries': 'Transportation',
  bcferries: 'Transportation',
  'via rail': 'Transportation',
  'air canada': 'Transportation',
  westjet: 'Transportation',
  'mobi bike': 'Transportation',
  'parking meter': 'Transportation',
  tolls: 'Transportation',
  // Subscriptions
  netflix: 'Subscriptions',
  spotify: 'Subscriptions',
  disney: 'Subscriptions',
  subscription: 'Subscriptions',
  'apple music': 'Subscriptions',
  'amazon prime': 'Subscriptions',
  youtube: 'Subscriptions',
  hulu: 'Subscriptions',
  hbo: 'Subscriptions',
  'apple tv': 'Subscriptions',
  microsoft: 'Subscriptions',
  adobe: 'Subscriptions',
  dropbox: 'Subscriptions',
  github: 'Subscriptions',
  chatgpt: 'Subscriptions',
  openai: 'Subscriptions',
  duolingo: 'Subscriptions',
  headspace: 'Subscriptions',
  calm: 'Subscriptions',
  icloud: 'Subscriptions',
  // Housing
  rent: 'Housing',
  mortgage: 'Housing',
  strata: 'Housing',
  hydro: 'Housing',
  utilities: 'Housing',
  insurance: 'Housing',
  'home insurance': 'Housing',
  'property tax': 'Housing',
  'bc hydro': 'Housing',
  enmax: 'Housing',
  bell: 'Housing',
  rogers: 'Housing',
  telus: 'Housing',
  shaw: 'Housing',
  internet: 'Housing',
  // Groceries
  groceries: 'Groceries',
  walmart: 'Groceries',
  costco: 'Groceries',
  superstore: 'Groceries',
  'save-on': 'Groceries',
  safeway: 'Groceries',
  'no frills': 'Groceries',
  'whole foods': 'Groceries',
  "trader joe's": 'Groceries',
  sobeys: 'Groceries',
  metro: 'Groceries',
  iga: 'Groceries',
  'food basics': 'Groceries',
  't&t': 'Groceries',
  'h-mart': 'Groceries',
  hmart: 'Groceries',
  produce: 'Groceries',
  market: 'Groceries',
  // Health
  doctor: 'Health',
  pharmacy: 'Health',
  prescription: 'Health',
  shoppers: 'Health',
  dentist: 'Health',
  clinic: 'Health',
  massage: 'Health',
  physio: 'Health',
  physiotherapy: 'Health',
  optometrist: 'Health',
  glasses: 'Health',
  contacts: 'Health',
  chiropractic: 'Health',
  hospital: 'Health',
  vitamin: 'Health',
  'urgent care': 'Health',
  'blood test': 'Health',
  // Fitness
  gym: 'Fitness',
  fitness: 'Fitness',
  yoga: 'Fitness',
  crossfit: 'Fitness',
  equinox: 'Fitness',
  goodlife: 'Fitness',
  'anytime fitness': 'Fitness',
  pilates: 'Fitness',
  peloton: 'Fitness',
  lululemon: 'Fitness',
  swimming: 'Fitness',
  spin: 'Fitness',
};
